In [52]:
import pandas as pd
import numpy as np
training_data = pd.read_csv("datasets/Training.csv")
testing_data = pd.read_csv("datasets/Testing.csv")
description_data = pd.read_csv("datasets/Symptoms_Description.csv",header=None)
precautions_data = pd.read_csv("datasets/Symptoms_Precautions.csv",header=None)

## Training_data Cleaning

In [41]:
training_data.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [42]:
for i in training_data.columns:
    print(f"{i} ---",training_data[i].isna().sum(),"     ||| Data type",training_data[i].dtype)

itching --- 0      ||| Data type int64
skin_rash --- 0      ||| Data type int64
nodal_skin_eruptions --- 0      ||| Data type int64
continuous_sneezing --- 0      ||| Data type int64
shivering --- 0      ||| Data type int64
chills --- 0      ||| Data type int64
joint_pain --- 0      ||| Data type int64
stomach_pain --- 0      ||| Data type int64
acidity --- 0      ||| Data type int64
ulcers_on_tongue --- 0      ||| Data type int64
muscle_wasting --- 0      ||| Data type int64
vomiting --- 0      ||| Data type int64
burning_micturition --- 0      ||| Data type int64
spotting_ urination --- 0      ||| Data type int64
fatigue --- 0      ||| Data type int64
weight_gain --- 0      ||| Data type int64
anxiety --- 0      ||| Data type int64
cold_hands_and_feets --- 0      ||| Data type int64
mood_swings --- 0      ||| Data type int64
weight_loss --- 0      ||| Data type int64
restlessness --- 0      ||| Data type int64
lethargy --- 0      ||| Data type int64
patches_in_throat --- 0      ||| Data type int64
irregular_sugar_level --- 0      ||| Data type int64
cough --- 0      ||| Data type int64
high_fever --- 0      ||| Data type int64
sunken_eyes --- 0      ||| Data type int64
breathlessness --- 0      ||| Data type int64
sweating --- 0      ||| Data type int64
dehydration --- 0      ||| Data type int64
indigestion --- 0      ||| Data type int64
headache --- 0      ||| Data type int64
yellowish_skin --- 0      ||| Data type int64
dark_urine --- 0      ||| Data type int64
nausea --- 0      ||| Data type int64
loss_of_appetite --- 0      ||| Data type int64
pain_behind_the_eyes --- 0      ||| Data type int64
back_pain --- 0      ||| Data type int64
constipation --- 0      ||| Data type int64
abdominal_pain --- 0      ||| Data type int64
diarrhoea --- 0      ||| Data type int64
mild_fever --- 0      ||| Data type int64
yellow_urine --- 0      ||| Data type int64
yellowing_of_eyes --- 0      ||| Data type int64
acute_liver_failure --- 0      ||| Data type int64
fluid_overload --- 0      ||| Data type int64
swelling_of_stomach --- 0      ||| Data type int64
swelled_lymph_nodes --- 0      ||| Data type int64
malaise --- 0      ||| Data type int64
blurred_and_distorted_vision --- 0      ||| Data type int64
phlegm --- 0      ||| Data type int64
throat_irritation --- 0      ||| Data type int64
redness_of_eyes --- 0      ||| Data type int64
sinus_pressure --- 0      ||| Data type int64
runny_nose --- 0      ||| Data type int64
congestion --- 0      ||| Data type int64
chest_pain --- 0      ||| Data type int64
weakness_in_limbs --- 0      ||| Data type int64
fast_heart_rate --- 0      ||| Data type int64
pain_during_bowel_movements --- 0      ||| Data type int64
pain_in_anal_region --- 0      ||| Data type int64
bloody_stool --- 0      ||| Data type int64
irritation_in_anus --- 0      ||| Data type int64
neck_pain --- 0      ||| Data type int64
dizziness --- 0      ||| Data type int64
cramps --- 0      ||| Data type int64
bruising --- 0      ||| Data type int64
obesity --- 0      ||| Data type int64
swollen_legs --- 0      ||| Data type int64
swollen_blood_vessels --- 0      ||| Data type int64
puffy_face_and_eyes --- 0      ||| Data type int64
enlarged_thyroid --- 0      ||| Data type int64
brittle_nails --- 0      ||| Data type int64
swollen_extremeties --- 0      ||| Data type int64
excessive_hunger --- 0      ||| Data type int64
extra_marital_contacts --- 0      ||| Data type int64
drying_and_tingling_lips --- 0      ||| Data type int64
slurred_speech --- 0      ||| Data type int64
knee_pain --- 0      ||| Data type int64
hip_joint_pain --- 0      ||| Data type int64
muscle_weakness --- 0      ||| Data type int64
stiff_neck --- 0      ||| Data type int64
swelling_joints --- 0      ||| Data type int64
movement_stiffness --- 0      ||| Data type int64
spinning_movements --- 0      ||| Data type int64
loss_of_balance --- 0      ||| Data type int64
unsteadiness --- 0      ||| Data type int64
weakness_of_one_body_side --- 0      ||| Data type int64
loss_of_smell --- 0      ||| Data type int64
bladder_discomfort --- 0      ||| Data type int64
foul_smell_of urine --- 0      ||| Data type int64
continuous_feel_of_urine --- 0      ||| Data type int64
passage_of_gases --- 0      ||| Data type int64
internal_itching --- 0      ||| Data type int64
toxic_look_(typhos) --- 0      ||| Data type int64
depression --- 0      ||| Data type int64
irritability --- 0      ||| Data type int64
muscle_pain --- 0      ||| Data type int64
altered_sensorium --- 0      ||| Data type int64
red_spots_over_body --- 0      ||| Data type int64
belly_pain --- 0      ||| Data type int64
abnormal_menstruation --- 0      ||| Data type int64
dischromic _patches --- 0      ||| Data type int64
watering_from_eyes --- 0      ||| Data type int64
increased_appetite --- 0      ||| Data type int64
polyuria --- 0      ||| Data type int64
family_history --- 0      ||| Data type int64
mucoid_sputum --- 0      ||| Data type int64
rusty_sputum --- 0      ||| Data type int64
lack_of_concentration --- 0      ||| Data type int64
visual_disturbances --- 0      ||| Data type int64
receiving_blood_transfusion --- 0      ||| Data type int64
receiving_unsterile_injections --- 0      ||| Data type int64
coma --- 0      ||| Data type int64
stomach_bleeding --- 0      ||| Data type int64
distention_of_abdomen --- 0      ||| Data type int64
history_of_alcohol_consumption --- 0      ||| Data type int64
fluid_overload.1 --- 0      ||| Data type int64
blood_in_sputum --- 0      ||| Data type int64
prominent_veins_on_calf --- 0      ||| Data type int64
palpitations --- 0      ||| Data type int64
painful_walking --- 0      ||| Data type int64
pus_filled_pimples --- 0      ||| Data type int64
blackheads --- 0      ||| Data type int64
scurring --- 0      ||| Data type int64
skin_peeling --- 0      ||| Data type int64
silver_like_dusting --- 0      ||| Data type int64
small_dents_in_nails --- 0      ||| Data type int64
inflammatory_nails --- 0      ||| Data type int64
blister --- 0      ||| Data type int64
red_sore_around_nose --- 0      ||| Data type int64
yellow_crust_ooze --- 0      ||| Data type int64
prognosis --- 0      ||| Data type object

In [43]:
print(training_data['prognosis'].unique())
print("Unique Count -",training_data['prognosis'].nunique())

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo']
Unique Count - 41

In [44]:
training_data['prognosis']=training_data['prognosis'].str.strip()

In [45]:
training_data.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,...,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000
mean,0.137805,0.159756,0.021951,0.045122,0.021951,0.162195,0.139024,0.045122,0.045122,0.021951,...,0.021951,0.021951,0.021951,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171
std,0.344730,0.366417,0.146539,0.207593,0.146539,0.368667,0.346007,0.207593,0.207593,0.146539,...,0.146539,0.146539,0.146539,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Testing dataset

In [46]:
testing_data.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction

In [47]:
for i in testing_data.columns:
    print(f"{i} ---",testing_data[i].isna().sum(),"............. Data type",testing_data[i].dtype)

itching --- 0 ............. Data type int64
skin_rash --- 0 ............. Data type int64
nodal_skin_eruptions --- 0 ............. Data type int64
continuous_sneezing --- 0 ............. Data type int64
shivering --- 0 ............. Data type int64
chills --- 0 ............. Data type int64
joint_pain --- 0 ............. Data type int64
stomach_pain --- 0 ............. Data type int64
acidity --- 0 ............. Data type int64
ulcers_on_tongue --- 0 ............. Data type int64
muscle_wasting --- 0 ............. Data type int64
vomiting --- 0 ............. Data type int64
burning_micturition --- 0 ............. Data type int64
spotting_ urination --- 0 ............. Data type int64
fatigue --- 0 ............. Data type int64
weight_gain --- 0 ............. Data type int64
anxiety --- 0 ............. Data type int64
cold_hands_and_feets --- 0 ............. Data type int64
mood_swings --- 0 ............. Data type int64
weight_loss --- 0 ............. Data type int64
restlessness --- 0 ............. Data type int64
lethargy --- 0 ............. Data type int64
patches_in_throat --- 0 ............. Data type int64
irregular_sugar_level --- 0 ............. Data type int64
cough --- 0 ............. Data type int64
high_fever --- 0 ............. Data type int64
sunken_eyes --- 0 ............. Data type int64
breathlessness --- 0 ............. Data type int64
sweating --- 0 ............. Data type int64
dehydration --- 0 ............. Data type int64
indigestion --- 0 ............. Data type int64
headache --- 0 ............. Data type int64
yellowish_skin --- 0 ............. Data type int64
dark_urine --- 0 ............. Data type int64
nausea --- 0 ............. Data type int64
loss_of_appetite --- 0 ............. Data type int64
pain_behind_the_eyes --- 0 ............. Data type int64
back_pain --- 0 ............. Data type int64
constipation --- 0 ............. Data type int64
abdominal_pain --- 0 ............. Data type int64
diarrhoea --- 0 ............. Data type int64
mild_fever --- 0 ............. Data type int64
yellow_urine --- 0 ............. Data type int64
yellowing_of_eyes --- 0 ............. Data type int64
acute_liver_failure --- 0 ............. Data type int64
fluid_overload --- 0 ............. Data type int64
swelling_of_stomach --- 0 ............. Data type int64
swelled_lymph_nodes --- 0 ............. Data type int64
malaise --- 0 ............. Data type int64
blurred_and_distorted_vision --- 0 ............. Data type int64
phlegm --- 0 ............. Data type int64
throat_irritation --- 0 ............. Data type int64
redness_of_eyes --- 0 ............. Data type int64
sinus_pressure --- 0 ............. Data type int64
runny_nose --- 0 ............. Data type int64
congestion --- 0 ............. Data type int64
chest_pain --- 0 ............. Data type int64
weakness_in_limbs --- 0 ............. Data type int64
fast_heart_rate --- 0 ............. Data type int64
pain_during_bowel_movements --- 0 ............. Data type int64
pain_in_anal_region --- 0 ............. Data type int64
bloody_stool --- 0 ............. Data type int64
irritation_in_anus --- 0 ............. Data type int64
neck_pain --- 0 ............. Data type int64
dizziness --- 0 ............. Data type int64
cramps --- 0 ............. Data type int64
bruising --- 0 ............. Data type int64
obesity --- 0 ............. Data type int64
swollen_legs --- 0 ............. Data type int64
swollen_blood_vessels --- 0 ............. Data type int64
puffy_face_and_eyes --- 0 ............. Data type int64
enlarged_thyroid --- 0 ............. Data type int64
brittle_nails --- 0 ............. Data type int64
swollen_extremeties --- 0 ............. Data type int64
excessive_hunger --- 0 ............. Data type int64
extra_marital_contacts --- 0 ............. Data type int64
drying_and_tingling_lips --- 0 ............. Data type int64
slurred_speech --- 0 ............. Data type int64
knee_pain --- 0 ............. Data type int64
hip_joint_pain --- 0 ............. Data type int64
muscle_weakness --- 0 ............. Data type int64
stiff_neck --- 0 ............. Data type int64
swelling_joints --- 0 ............. Data type int64
movement_stiffness --- 0 ............. Data type int64
spinning_movements --- 0 ............. Data type int64
loss_of_balance --- 0 ............. Data type int64
unsteadiness --- 0 ............. Data type int64
weakness_of_one_body_side --- 0 ............. Data type int64
loss_of_smell --- 0 ............. Data type int64
bladder_discomfort --- 0 ............. Data type int64
foul_smell_of urine --- 0 ............. Data type int64
continuous_feel_of_urine --- 0 ............. Data type int64
passage_of_gases --- 0 ............. Data type int64
internal_itching --- 0 ............. Data type int64
toxic_look_(typhos) --- 0 ............. Data type int64
depression --- 0 ............. Data type int64
irritability --- 0 ............. Data type int64
muscle_pain --- 0 ............. Data type int64
altered_sensorium --- 0 ............. Data type int64
red_spots_over_body --- 0 ............. Data type int64
belly_pain --- 0 ............. Data type int64
abnormal_menstruation --- 0 ............. Data type int64
dischromic _patches --- 0 ............. Data type int64
watering_from_eyes --- 0 ............. Data type int64
increased_appetite --- 0 ............. Data type int64
polyuria --- 0 ............. Data type int64
family_history --- 0 ............. Data type int64
mucoid_sputum --- 0 ............. Data type int64
rusty_sputum --- 0 ............. Data type int64
lack_of_concentration --- 0 ............. Data type int64
visual_disturbances --- 0 ............. Data type int64
receiving_blood_transfusion --- 0 ............. Data type int64
receiving_unsterile_injections --- 0 ............. Data type int64
coma --- 0 ............. Data type int64
stomach_bleeding --- 0 ............. Data type int64
distention_of_abdomen --- 0 ............. Data type int64
history_of_alcohol_consumption --- 0 ............. Data type int64
fluid_overload.1 --- 0 ............. Data type int64
blood_in_sputum --- 0 ............. Data type int64
prominent_veins_on_calf --- 0 ............. Data type int64
palpitations --- 0 ............. Data type int64
painful_walking --- 0 ............. Data type int64
pus_filled_pimples --- 0 ............. Data type int64
blackheads --- 0 ............. Data type int64
scurring --- 0 ............. Data type int64
skin_peeling --- 0 ............. Data type int64
silver_like_dusting --- 0 ............. Data type int64
small_dents_in_nails --- 0 ............. Data type int64
inflammatory_nails --- 0 ............. Data type int64
blister --- 0 ............. Data type int64
red_sore_around_nose --- 0 ............. Data type int64
yellow_crust_ooze --- 0 ............. Data type int64
prognosis --- 0 ............. Data type object

In [48]:
print(testing_data['prognosis'].unique())
print("Unique Count -",testing_data['prognosis'].nunique())

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo']
Unique Count - 41

## Description Data

In [49]:
description_data.head()

                0                                                  1
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [29]:
description_data[0].unique()

array(['Drug Reaction', 'Malaria', 'Allergy', 'Hypothyroidism',
       'Psoriasis', 'GERD', 'Chronic cholestasis', 'hepatitis A',
       'Osteoarthristis', '(vertigo) Paroymsal  Positional Vertigo',
       'Hypoglycemia', 'Acne', 'Diabetes', 'Impetigo', 'Hypertension',
       'Peptic ulcer diseae', 'Dimorphic hemorrhoids(piles)',
       'Common Cold', 'Chicken pox', 'Cervical spondylosis',
       'Hyperthyroidism', 'Urinary tract infection', 'Varicose veins',
       'AIDS', 'Paralysis (brain hemorrhage)', 'Typhoid', 'Hepatitis B',
       'Fungal infection', 'Hepatitis C', 'Migraine', 'Bronchial Asthma',
       'Alcoholic hepatitis', 'Jaundice', 'Hepatitis E', 'Dengue',
       'Hepatitis D', 'Heart attack', 'Pneumonia', 'Arthritis',
       'Gastroenteritis', 'Tuberculosis'], dtype=object)

In [30]:
description_data[0]=description_data[0].str.strip()

In [38]:
description_data[1]=description_data[1].str.strip()

In [39]:
description_data.head()

                0                                                  1
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

## Precautions Data

In [58]:
precautions_data.sample(10)

,0,1,2,3,4
10,Hypoglycemia,lie down on side,check in pulse,drink sugary drinks,consult doctor
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
38,Arthritis,exercise,use hot and cold therapy,try acupuncture,massage
2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
29,Migraine,meditation,reduce stress,use poloroid glasses in sun,consult doctor
31,Alcoholic hepatitis,stop alcohol consumption,consult doctor,medication,follow up
30,Bronchial Asthma,switch to loose cloothing,take deep breaths,get away from trigger,seek help
23,AIDS,avoid open cuts,wear ppe if possible,consult doctor,follow up
11,Acne,bath twice,avoid fatty spicy food,drink plenty of water,avoid too many products
26,Hepatitis B,consult nearest hospital,vaccination,eat healthy,medication

In [60]:
precautions_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       41 non-null     object
 1   1       41 non-null     object
 2   2       41 non-null     object
 3   3       40 non-null     object
 4   4       40 non-null     object
dtypes: object(5)
memory usage: 1.7+ KB

### Found Null values in column 3 & 4

In [63]:
print(precautions_data[3].isna().sum())
print(precautions_data[4].isna().sum())

1
1

### filling empty cells with "rest"

In [66]:
precautions_data[3]=precautions_data[3].fillna('rest')
precautions_data[4]=precautions_data[4].fillna('rest')

In [69]:
precautions_data[0]=precautions_data[0].str.strip()
precautions_data[1]=precautions_data[1].str.strip()
precautions_data[2]=precautions_data[2].str.strip()
precautions_data[3]=precautions_data[3].str.strip()
precautions_data[4]=precautions_data[4].str.strip()

In [70]:
precautions_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       41 non-null     object
 1   1       41 non-null     object
 2   2       41 non-null     object
 3   3       41 non-null     object
 4   4       41 non-null     object
dtypes: object(5)
memory usage: 1.7+ KB

In [71]:
precautions_data.describe()

,0,1,2,3,4
count,41,41,41,41,41
unique,41,32,34,30,24
top,Drug Reaction,Consult nearest hospital,exercise,consult doctor,follow up
freq,1,3,3,6,6

## Converting cleaned data into new CSV files

In [73]:
training_data.to_csv("Cleaned datasets/Training data.csv",index=False)
testing_data.to_csv("Cleaned datasets/Testing data.csv",index=False)
description_data.to_csv("Cleaned datasets/Description data.csv",index=False)
precautions_data.to_csv("Cleaned datasets/Precautions data.csv",index=False)